version: '3.7'
services:
  scrap_backend:
    container_name: scrap_backend
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - redis
    command: yarn run start:dev
    env_file:
      - .env.docker
  redis:
    image: redis:alpine
    container_name: scrap_backend-redis
    restart: always
    command: redis-server --save 20 1 --requirepass root
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
volumes:
  redis-data:
    driver: local