import { config } from 'dotenv'

config()
const {
  PORT,
  REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT,
  NODE_ENV,
  CACHE_EXPIRES_SECONDS,
  USERNAME,
  ACTIVE_DEBUG,
  AXIOS_TIMEOUT
} = process.env

export const envs = {
  PORT: PORT,
  NODE_ENV: NODE_ENV,
  redis: {
    USERNAME: USERNAME,
    REDIS_HOST: REDIS_HOST,
    REDIS_PASSWORD: REDIS_PASSWORD,
    REDIS_PORT: REDIS_PORT,
    CACHE_EXPIRES_SECONDS: CACHE_EXPIRES_SECONDS
  },
  ACTIVE_DEBUG: ACTIVE_DEBUG,
  AXIOS_TIMEOUT: AXIOS_TIMEOUT
}
